import { shortestJobFirst } from '../../src/libs/sjf';

it(`Should work`, () => {
	expect(
		shortestJobFirst([
			['P2', 1, 5],
			['P3', 8, 8],
			['P6', 0, 6],
			['P4', 6, 9],
			['P5', 3, 1],
			['P1', 0, 5],
			['P0', 0, 5],
			['P7', 0, 5],
		])
	).toStrictEqual({
		infos: [
			{
				pid: 'P0',
				arrivalTime: 0,
				burstTime: 5,
				startTime: 0,
				finishTime: 5,
				responseTime: 0,
				turnaroundTime: 5,
				waitTime: 0,
			},
			{
				pid: 'P5',
				arrivalTime: 3,
				burstTime: 1,
				startTime: 5,
				finishTime: 6,
				responseTime: 2,
				turnaroundTime: 3,
				waitTime: 2,
			},
			{
				pid: 'P0',
				arrivalTime: 0,
				burstTime: 5,
				startTime: 6,
				finishTime: 11,
				responseTime: 6,
				turnaroundTime: 11,
				waitTime: 6,
			},
			{
				pid: 'P1',
				arrivalTime: 0,
				burstTime: 5,
				startTime: 11,
				finishTime: 16,
				responseTime: 11,
				turnaroundTime: 16,
				waitTime: 11,
			},
			{
				pid: 'P2',
				arrivalTime: 1,
				burstTime: 5,
				startTime: 16,
				finishTime: 21,
				responseTime: 15,
				turnaroundTime: 20,
				waitTime: 15,
			},
			{
				pid: 'P6',
				arrivalTime: 0,
				burstTime: 6,
				startTime: 21,
				finishTime: 27,
				responseTime: 21,
				turnaroundTime: 27,
				waitTime: 21,
			},
			{
				pid: 'P3',
				arrivalTime: 8,
				burstTime: 8,
				startTime: 27,
				finishTime: 35,
				responseTime: 19,
				turnaroundTime: 27,
				waitTime: 19,
			},
			{
				pid: 'P4',
				arrivalTime: 6,
				burstTime: 9,
				startTime: 35,
				finishTime: 44,
				responseTime: 29,
				turnaroundTime: 38,
				waitTime: 29,
			},
		],
		averageResponseTime: 12.875,
		totalResponseTime: 103,
		averageWaitTime: 12.875,
		totalWaitTime: 103,
		averageTurnaroundTime: 18.375,
		totalTurnaroundTime: 147,
	});
});
